config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages, only: [:index, :show, :create]

  get 'dashboard' => 'dashboard#index'

  resources :users do
    member do
      post  'follow'
      post  'unfollow'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          get 'messages'
          get 'followers'
          get 'following'
        end
      end
    end
  end

  root 'dashboard#index'

end

app/models/message.rb
# message.rb
class Message < ActiveRecord::Base
  belongs_to :owner, class_name: 'User'
  validates :owner_id, :body, presence: true, allow_nil: false, allow_blank: false
  validates :body, length: { maximum: 160 }

  before_validation :sanitize_input

  def sanitize_input
    body.gsub!('\r\n', '') if body.present?
  end
end

app/controllers/messages_controller.rb
# messages_controller.rb
class MessagesController < SecuredController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.includes(:owner).all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.includes(:owner).find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def message_params
    params.require(:message).permit(:body, :owner_id)
  end
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/create.js.erb
<% if @message.errors.any? %>
	$('#success_explanation').remove();
	$('#error_explanation').remove();
	$('.new_message .field').removeClass('field_with_errors');
	$('.new_message .field').addClass('field_with_errors');
	$('form').prepend('<div id="error_explanation"><h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2><ul><% @message.errors.full_messages.each do |message| %><li><%= message %></li><% end %></ul></div>');
<% else %>
	$('#error_explanation').remove();
	$('.new_message .field').removeClass('field_with_errors');
//	$('form').prepend('<div id="success_explanation"><h2>Published</h2></div>');
	document.getElementById('message').value = "";
	$('#activities').prepend('<li><%= escape_javascript render :partial => 'dashboard/post', locals: {message: @message} %></li>')
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Messages</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.body %></td>
        <td><%= message.owner.username %></td>
        <td><%= link_to 'Show', message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
Message by <%= link_to @message.owner.username, @message.owner, {"onclick" => "ga('send', 'event', 'button', 'user_show');return true;"} %>:
</p>

<%= @message.body %>