config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages, only: [:index, :show, :create]

  get 'dashboard' => 'dashboard#index'

  resources :users do
    member do
      post  'follow'
      post  'unfollow'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          get 'messages'
          get 'followers'
          get 'following'
        end
      end
    end
  end

  root 'dashboard#index'

end

app/models/user.rb
# user.rb
class User < ActiveRecord::Base
  validates :username, :email, :password, presence: true
  validates :username, uniqueness: true

  has_many :messages, inverse_of: :owner, foreign_key: :owner_id

  has_many :relationships, foreign_key: :follower_id
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followed_id

  has_many :followings, class_name: 'User', through: 'relationships', source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  def publish(message)
    messages.create(body: message)
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    # users_controller.rb
    class UsersController < Api::V1::BaseController
      def messages
        @messages = User.find(params[:id]).messages.select(:id, :owner_id, :body, :created_at)
        render json: @messages
      end

      def followers
        @followers = User.find(params[:id]).followers.select(:id, :username, :email)
        render json: @followers
      end

      def following
        @follwing = User.find(params[:id]).followings.select(:id, :username, :email)
        render json: @follwing
      end
    end
  end
end

app/controllers/users_controller.rb
# users_controller.rb
class UsersController < SecuredController
  before_action :authenticate_user, except: [:new, :create]
  before_action :set_user, only: [:show, :follow, :unfollow]
  before_action :set_current_user, only: [:edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.includes(:messages).all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def follow
    respond_to do |format|
      if @current_user.relationships.create(followed_id: params[:id])
        format.js
      else
        format.js
      end
    end
  end

  def unfollow
    @relationship = @current_user.relationships.find_by_followed_id(params[:id])
    puts @relationship.inspect
    @relationship.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.includes(:messages).find(params[:id])
  end

  def set_current_user
    @user = @current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :username, :password)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "onclick" => "ga('send', 'event', 'button', 'register');return true;" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Your Pofile</h1>

<%= render 'form' %>

app/views/users/follow.js.erb
$('.<%= @current_user.id.to_s + '_' + params[:id]%>').replaceWith('<%= unfollow_user(@user) %>');
$('#following').append('<%= escape_javascript render( partial: 'dashboard/user', locals: {user: @user}) %>');

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registered Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Follow?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
		<td><%= user.email %></td>
        <td><%= follow_or_unfollow_user(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<%= follow_or_unfollow_user(@user) %>
<h3>Posts</h3>
<ul>
  <% @user.messages.each do |message| %>
  	<li><%= message.body %> (<%= message.created_at %>)</li>
  <% end %>
</ul>

<%= link_to 'Back', dashboard_path %>

app/views/users/unfollow.js.erb
$('.<%= @current_user.id.to_s + '_' + params[:id]%>').replaceWith('<%= follow_user(@user) %>');
$('#<%= @user.id %>').remove();