config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages, only: [:index, :show, :create]

  get 'dashboard' => 'dashboard#index'

  resources :users do
    member do
      post  'follow'
      post  'unfollow'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users do
        member do
          get 'messages'
          get 'followers'
          get 'following'
        end
      end
    end
  end

  root 'dashboard#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Platform161Twitter</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="main">
  <% if @current_user %>
	  Welcome <%= link_to @current_user.username , edit_user_path(@current_user), {"onclick" => "ga('send', 'event', 'button', 'nav_profile');return true;"} %> |
	  <%= link_to 'Dashboard', root_path, {"onclick" => "ga('send', 'event', 'button', 'nav_dashboard');return true;"} %> |
	  <%= link_to 'Users', users_path, {"onclick" => "ga('send', 'event', 'button', 'nav_users');return true;"} %> |
	  <%= link_to 'Logout', session_path(@current_user.id), {:method => :delete, "onclick" => "ga('send', 'event', 'button', 'nav_logout');return true;"} %>
  <% else %>
	  <%= link_to 'Please log in', new_session_path, {"onclick" => "ga('send', 'event', 'button', 'nav_login');return true;"} %> |
	  <%= link_to 'Register', new_user_path, {"onclick" => "ga('send', 'event', 'button', 'nav_register');return true;"} %>
  <% end %>
  <%= yield %>
</div>

<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-63303600-1', 'auto');
	ga('send', 'pageview');

</script>
<script>
  !function(g,s,q,r,d){r=g[r]=g[r]||function(){(r.q=r.q||[]).push(
  arguments)};d=s.createElement(q);q=s.getElementsByTagName(q)[0];
  d.src='//d1l6p2sc9645hc.cloudfront.net/tracker.js';q.parentNode.
  insertBefore(d,q)}(window,document,'script','_gs');

  _gs('GSN-145394-X');
  <% if @current_user %>
  	_gs('identify', <%= @current_user.id %>);
  <% end %>
</script>
</body>
</html>